import { FileData } from "../store/types";

export const exampleData: FileData = [
  {
    first_name: "Alice",
    last_name: "Johnson",
    id: "10001",
    email: "alice.johnson@example.com",
    gender: "Female",
  },
  {
    first_name: "Bob",
    last_name: "Williams",
    id: "10002",
    email: "bob.williams@example.com",
    gender: "Male",
  },
  {
    first_name: "Charlie",
    last_name: "Brown",
    id: "10003",
    email: "charlie.brown@example.com",
    gender: "Male",
  },
  {
    first_name: "David",
    last_name: "Miller",
    id: "10004",
    email: "david.miller@example.com",
    gender: "Male",
  },
  {
    first_name: "Emily",
    last_name: "Garcia",
    id: "10005",
    email: "emily.garcia@example.com",
    gender: "Female",
  },
  {
    first_name: "Olivia",
    last_name: "Young",
    id: "10100",
    email: "olivia.young@example.com",
    gender: "Female",
  },
  {
    first_name: "Sophia",
    last_name: "Thomas",
    id: "10101",
    email: "sophia.thomas@example.com",
    gender: "Female",
  },
  {
    first_name: "Isabella",
    last_name: "Martin",
    id: "10102",
    email: "isabella.martin@example.com",
    gender: "Female",
  },
  {
    first_name: "Ava",
    last_name: "Lewis",
    id: "10103",
    email: "ava.lewis@example.com",
    gender: "Female",
  },
  {
    first_name: "Mia",
    last_name: "Clark",
    id: "10104",
    email: "mia.clark@example.com",
    gender: "Female",
  },
  {
    first_name: "William",
    last_name: "Gonzalez",
    id: "10006",
    email: "william.gonzalez@example.com",
    gender: "Male",
  },
  {
    first_name: "James",
    last_name: "Lopez",
    id: "10007",
    email: "james.lopez@example.com",
    gender: "Male",
  },
  {
    first_name: "Benjamin",
    last_name: "Hernandez",
    id: "10008",
    email: "benjamin.hernandez@example.com",
    gender: "Male",
  },
  {
    first_name: "Lucas",
    last_name: "Rodriguez",
    id: "10009",
    email: "lucas.rodriguez@example.com",
    gender: "Male",
  },
  {
    first_name: "Mason",
    last_name: "Walker",
    id: "10010",
    email: "mason.walker@example.com",
    gender: "Male",
  },
  {
    first_name: "Ethan",
    last_name: "Allen",
    id: "10011",
    email: "ethan.allen@example.com",
    gender: "Male",
  },
  {
    first_name: "Aiden",
    last_name: "Wright",
    id: "10012",
    email: "aiden.wright@example.com",
    gender: "Male",
  },
  {
    first_name: "Daniel",
    last_name: "Scott",
    id: "10013",
    email: "daniel.scott@example.com",
    gender: "Male",
  },
  {
    first_name: "Matthew",
    last_name: "Robinson",
    id: "10014",
    email: "matthew.robinson@example.com",
    gender: "Male",
  },
  {
    first_name: "Joseph",
    last_name: "Young",
    id: "10015",
    email: "joseph.young@example.com",
    gender: "Male",
  },
  {
    first_name: "Elijah",
    last_name: "King",
    id: "10016",
    email: "elijah.king@example.com",
    gender: "Male",
  },
  {
    first_name: "Alexander",
    last_name: "Lee",
    id: "10017",
    email: "alexander.lee@example.com",
    gender: "Male",
  },
  {
    first_name: "Jackson",
    last_name: "Wood",
    id: "10018",
    email: "jackson.wood@example.com",
    gender: "Male",
  },
  {
    first_name: "Anthony",
    last_name: "Hall",
    id: "10019",
    email: "anthony.hall@example.com",
    gender: "Male",
  },
  {
    first_name: "Jacob",
    last_name: "Hill",
    id: "10020",
    email: "jacob.hill@example.com",
    gender: "Male",
  },
  {
    first_name: "Noah",
    last_name: "Nelson",
    id: "10021",
    email: "noah.nelson@example.com",
    gender: "Male",
  },
  {
    first_name: "Michael",
    last_name: "Baker",
    id: "10022",
    email: "michael.baker@example.com",
    gender: "Male",
  },
  {
    first_name: "Andrew",
    last_name: "Harris",
    id: "10023",
    email: "andrew.harris@example.com",
    gender: "Male",
  },
  {
    first_name: "Joshua",
    last_name: "Campbell",
    id: "10024",
    email: "joshua.campbell@example.com",
    gender: "Male",
  },
  {
    first_name: "Samuel",
    last_name: "Mitchell",
    id: "10025",
    email: "samuel.mitchell@example.com",
    gender: "Male",
  },
  {
    first_name: "Gabriel",
    last_name: "Carter",
    id: "10026",
    email: "gabriel.carter@example.com",
    gender: "Male",
  },
  {
    first_name: "Daniel",
    last_name: "Richardson",
    id: "10027",
    email: "daniel.richardson@example.com",
    gender: "Male",
  },
  {
    first_name: "Christopher",
    last_name: "Lewis",
    id: "10028",
    email: "christopher.lewis@example.com",
    gender: "Male",
  },
  {
    first_name: "John",
    last_name: "Moore",
    id: "10029",
    email: "john.moore@example.com",
    gender: "Male",
  },
  {
    first_name: "David",
    last_name: "Clark",
    id: "10030",
    email: "david.clark@example.com",
    gender: "Male",
  },
  {
    first_name: "Aiden",
    last_name: "Robinson",
    id: "10031",
    email: "aiden.robinson@example.com",
    gender: "Male",
  },
  {
    first_name: "Matthew",
    last_name: "Young",
    id: "10032",
    email: "matthew.young@example.com",
    gender: "Male",
  },
  {
    first_name: "Joseph",
    last_name: "Wright",
    id: "10033",
    email: "joseph.wright@example.com",
    gender: "Male",
  },
  {
    first_name: "Jackson",
    last_name: "Allen",
    id: "10034",
    email: "jackson.allen@example.com",
    gender: "Male",
  },
  {
    first_name: "William",
    last_name: "Scott",
    id: "10035",
    email: "william.scott@example.com",
    gender: "Male",
  },
  {
    first_name: "Benjamin",
    last_name: "Lee",
    id: "10036",
    email: "benjamin.lee@example.com",
    gender: "Male",
  },
  {
    first_name: "James",
    last_name: "Nelson",
    id: "10037",
    email: "james.nelson@example.com",
    gender: "Male",
  },
  {
    first_name: "Lucas",
    last_name: "Baker",
    id: "10038",
    email: "lucas.baker@example.com",
    gender: "Male",
  },
  {
    first_name: "Mason",
    last_name: "Harris",
    id: "10039",
    email: "mason.harris@example.com",
    gender: "Male",
  },
  {
    first_name: "Ethan",
    last_name: "Campbell",
    id: "10040",
    email: "ethan.campbell@example.com",
    gender: "Male",
  },
  {
    first_name: "Aiden",
    last_name: "Mitchell",
    id: "10041",
    email: "aiden.mitchell@example.com",
    gender: "Male",
  },
  {
    first_name: "Daniel",
    last_name: "Carter",
    id: "10042",
    email: "daniel.carter@example.com",
    gender: "Male",
  },
];
